name: torch_serving
channels:
  - pytorch-nightly
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  - pip:
      - ultralytics==8.0.89
      - pandas
# prefix: /home/aziz/anaconda3/envs/torch_serving
